package xyz.lejon.r.rmath;
import com.sun.jna.Library;
import com.sun.jna.Native;
import com.sun.jna.NativeLibrary;
import com.sun.jna.ptr.DoubleByReference;
import com.sun.jna.ptr.IntByReference;
import java.nio.DoubleBuffer;
import java.nio.IntBuffer;
/**
 * JNA Wrapper for library <b>Rmath</b><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public interface RmathLibrary extends Library {
	public static final String JNA_LIBRARY_NAME = "Rmath";
	public static final NativeLibrary JNA_NATIVE_LIB = NativeLibrary.getInstance(RmathLibrary.JNA_LIBRARY_NAME);
	public static final RmathLibrary INSTANCE = (RmathLibrary)Native.loadLibrary(RmathLibrary.JNA_LIBRARY_NAME, RmathLibrary.class);
	/**
	 * <i>native declaration : /Users/eralljn/Research/Coding/C/Rlibs/R.framework/Versions/3.2/Resources/include/Rmath.h</i><br>
	 * enum values
	 */
	public static interface Rboolean {
		/** <i>native declaration : /Users/eralljn/Research/Coding/C/Rlibs/R.framework/Versions/3.2/Resources/include/Rmath.h:161</i> */
		public static final int FALSE = 0;
		/** <i>native declaration : /Users/eralljn/Research/Coding/C/Rlibs/R.framework/Versions/3.2/Resources/include/Rmath.h:161</i> */
		public static final int TRUE = 1;
	};
	/** <i>native declaration : /Users/eralljn/Research/Coding/C/Rlibs/R.framework/Versions/3.2/Resources/include/Rmath.h</i> */
	public static final int __STDC_WANT_IEC_60559_TYPES_EXT__ = (int)1;
	/** <i>native declaration : /Users/eralljn/Research/Coding/C/Rlibs/R.framework/Versions/3.2/Resources/include/Rmath.h</i> */
	public static final String R_VERSION_STRING = (String)"3.2.1";
	/** <i>native declaration : /Users/eralljn/Research/Coding/C/Rlibs/R.framework/Versions/3.2/Resources/include/Rmath.h</i> */
	public static final int HAVE_EXPM1 = (int)1;
	/** <i>native declaration : /Users/eralljn/Research/Coding/C/Rlibs/R.framework/Versions/3.2/Resources/include/Rmath.h</i> */
	public static final int HAVE_HYPOT = (int)1;
	/** <i>native declaration : /Users/eralljn/Research/Coding/C/Rlibs/R.framework/Versions/3.2/Resources/include/Rmath.h</i> */
	public static final int HAVE_LOG1P = (int)1;
	/** <i>native declaration : /Users/eralljn/Research/Coding/C/Rlibs/R.framework/Versions/3.2/Resources/include/Rmath.h</i> */
	public static final int HAVE_WORKING_LOG1P = (int)1;
	/** <i>native declaration : /Users/eralljn/Research/Coding/C/Rlibs/R.framework/Versions/3.2/Resources/include/Rmath.h</i> */
	public static final double M_E = (double)2.718281828459045235360287471353;
	/** <i>native declaration : /Users/eralljn/Research/Coding/C/Rlibs/R.framework/Versions/3.2/Resources/include/Rmath.h</i> */
	public static final double M_LOG2E = (double)1.442695040888963407359924681002;
	/** <i>native declaration : /Users/eralljn/Research/Coding/C/Rlibs/R.framework/Versions/3.2/Resources/include/Rmath.h</i> */
	public static final double M_LOG10E = (double)0.434294481903251827651128918917;
	/** <i>native declaration : /Users/eralljn/Research/Coding/C/Rlibs/R.framework/Versions/3.2/Resources/include/Rmath.h</i> */
	public static final double M_LN2 = (double)0.693147180559945309417232121458;
	/** <i>native declaration : /Users/eralljn/Research/Coding/C/Rlibs/R.framework/Versions/3.2/Resources/include/Rmath.h</i> */
	public static final double M_LN10 = (double)2.302585092994045684017991454684;
	/** <i>native declaration : /Users/eralljn/Research/Coding/C/Rlibs/R.framework/Versions/3.2/Resources/include/Rmath.h</i> */
	public static final double M_PI = (double)3.141592653589793238462643383280;
	/** <i>native declaration : /Users/eralljn/Research/Coding/C/Rlibs/R.framework/Versions/3.2/Resources/include/Rmath.h</i> */
	public static final double M_2PI = (double)6.283185307179586476925286766559;
	/** <i>native declaration : /Users/eralljn/Research/Coding/C/Rlibs/R.framework/Versions/3.2/Resources/include/Rmath.h</i> */
	public static final double M_PI_2 = (double)1.570796326794896619231321691640;
	/** <i>native declaration : /Users/eralljn/Research/Coding/C/Rlibs/R.framework/Versions/3.2/Resources/include/Rmath.h</i> */
	public static final double M_PI_4 = (double)0.785398163397448309615660845820;
	/** <i>native declaration : /Users/eralljn/Research/Coding/C/Rlibs/R.framework/Versions/3.2/Resources/include/Rmath.h</i> */
	public static final double M_1_PI = (double)0.318309886183790671537767526745;
	/** <i>native declaration : /Users/eralljn/Research/Coding/C/Rlibs/R.framework/Versions/3.2/Resources/include/Rmath.h</i> */
	public static final double M_2_PI = (double)0.636619772367581343075535053490;
	/** <i>native declaration : /Users/eralljn/Research/Coding/C/Rlibs/R.framework/Versions/3.2/Resources/include/Rmath.h</i> */
	public static final double M_2_SQRTPI = (double)1.128379167095512573896158903122;
	/** <i>native declaration : /Users/eralljn/Research/Coding/C/Rlibs/R.framework/Versions/3.2/Resources/include/Rmath.h</i> */
	public static final double M_SQRT2 = (double)1.414213562373095048801688724210;
	/** <i>native declaration : /Users/eralljn/Research/Coding/C/Rlibs/R.framework/Versions/3.2/Resources/include/Rmath.h</i> */
	public static final double M_SQRT1_2 = (double)0.707106781186547524400844362105;
	/** <i>native declaration : /Users/eralljn/Research/Coding/C/Rlibs/R.framework/Versions/3.2/Resources/include/Rmath.h</i> */
	public static final double M_SQRT_3 = (double)1.732050807568877293527446341506;
	/** <i>native declaration : /Users/eralljn/Research/Coding/C/Rlibs/R.framework/Versions/3.2/Resources/include/Rmath.h</i> */
	public static final double M_SQRT_32 = (double)5.656854249492380195206754896838;
	/** <i>native declaration : /Users/eralljn/Research/Coding/C/Rlibs/R.framework/Versions/3.2/Resources/include/Rmath.h</i> */
	public static final double M_LOG10_2 = (double)0.301029995663981195213738894724;
	/** <i>native declaration : /Users/eralljn/Research/Coding/C/Rlibs/R.framework/Versions/3.2/Resources/include/Rmath.h</i> */
	public static final double M_SQRT_PI = (double)1.772453850905516027298167483341;
	/** <i>native declaration : /Users/eralljn/Research/Coding/C/Rlibs/R.framework/Versions/3.2/Resources/include/Rmath.h</i> */
	public static final double M_1_SQRT_2PI = (double)0.398942280401432677939946059934;
	/** <i>native declaration : /Users/eralljn/Research/Coding/C/Rlibs/R.framework/Versions/3.2/Resources/include/Rmath.h</i> */
	public static final double M_SQRT_2dPI = (double)0.797884560802865355879892119869;
	/** <i>native declaration : /Users/eralljn/Research/Coding/C/Rlibs/R.framework/Versions/3.2/Resources/include/Rmath.h</i> */
	public static final double M_LN_2PI = (double)1.837877066409345483560659472811;
	/** <i>native declaration : /Users/eralljn/Research/Coding/C/Rlibs/R.framework/Versions/3.2/Resources/include/Rmath.h</i> */
	public static final double M_LN_SQRT_PI = (double)0.572364942924700087071713675677;
	/** <i>native declaration : /Users/eralljn/Research/Coding/C/Rlibs/R.framework/Versions/3.2/Resources/include/Rmath.h</i> */
	public static final double M_LN_SQRT_2PI = (double)0.918938533204672741780329736406;
	/** <i>native declaration : /Users/eralljn/Research/Coding/C/Rlibs/R.framework/Versions/3.2/Resources/include/Rmath.h</i> */
	public static final double M_LN_SQRT_PId2 = (double)0.225791352644727432363097614947;
	/**
	 * Original signature : <code>double R_pow(double, double)</code><br>
	 * <i>native declaration : /Users/eralljn/Research/Coding/C/Rlibs/R.framework/Versions/3.2/Resources/include/Rmath.h:321</i>
	 */
	double R_pow(double x, double y);
	/**
	 * Original signature : <code>double R_pow_di(double, int)</code><br>
	 * <i>native declaration : /Users/eralljn/Research/Coding/C/Rlibs/R.framework/Versions/3.2/Resources/include/Rmath.h:322</i>
	 */
	double R_pow_di(double double1, int int1);
	/**
	 * Original signature : <code>double norm_rand()</code><br>
	 * <i>native declaration : /Users/eralljn/Research/Coding/C/Rlibs/R.framework/Versions/3.2/Resources/include/Rmath.h:326</i>
	 */
	double norm_rand();
	/**
	 * Original signature : <code>double unif_rand()</code><br>
	 * <i>native declaration : /Users/eralljn/Research/Coding/C/Rlibs/R.framework/Versions/3.2/Resources/include/Rmath.h:327</i>
	 */
	double unif_rand();
	/**
	 * Original signature : <code>double exp_rand()</code><br>
	 * <i>native declaration : /Users/eralljn/Research/Coding/C/Rlibs/R.framework/Versions/3.2/Resources/include/Rmath.h:328</i>
	 */
	double exp_rand();
	/**
	 * Original signature : <code>void set_seed(unsigned int, unsigned int)</code><br>
	 * <i>native declaration : /Users/eralljn/Research/Coding/C/Rlibs/R.framework/Versions/3.2/Resources/include/Rmath.h:330</i>
	 */
	void set_seed(int int1, int int2);
	/**
	 * Original signature : <code>void get_seed(unsigned int*, unsigned int*)</code><br>
	 * <i>native declaration : /Users/eralljn/Research/Coding/C/Rlibs/R.framework/Versions/3.2/Resources/include/Rmath.h:331</i><br>
	 * @deprecated use the safer methods {@link #get_seed(java.nio.IntBuffer, java.nio.IntBuffer)} and {@link #get_seed(com.sun.jna.ptr.IntByReference, com.sun.jna.ptr.IntByReference)} instead
	 */
	@Deprecated 
	void get_seed(IntByReference intPtr1, IntByReference intPtr2);
	/**
	 * Original signature : <code>void get_seed(unsigned int*, unsigned int*)</code><br>
	 * <i>native declaration : /Users/eralljn/Research/Coding/C/Rlibs/R.framework/Versions/3.2/Resources/include/Rmath.h:331</i>
	 */
	void get_seed(IntBuffer intPtr1, IntBuffer intPtr2);
	/**
	 * Original signature : <code>double dnorm4(double, double, double, int)</code><br>
	 * <i>native declaration : /Users/eralljn/Research/Coding/C/Rlibs/R.framework/Versions/3.2/Resources/include/Rmath.h:336</i>
	 */
	double dnorm4(double double1, double double2, double double3, int int1);
	/**
	 * Original signature : <code>double pnorm5(double, double, double, int, int)</code><br>
	 * <i>native declaration : /Users/eralljn/Research/Coding/C/Rlibs/R.framework/Versions/3.2/Resources/include/Rmath.h:337</i>
	 */
	double pnorm5(double double1, double double2, double double3, int int1, int int2);
	/**
	 * Original signature : <code>double qnorm5(double, double, double, int, int)</code><br>
	 * <i>native declaration : /Users/eralljn/Research/Coding/C/Rlibs/R.framework/Versions/3.2/Resources/include/Rmath.h:338</i>
	 */
	double qnorm5(double double1, double double2, double double3, int int1, int int2);
	/**
	 * Original signature : <code>double rnorm(double, double)</code><br>
	 * <i>native declaration : /Users/eralljn/Research/Coding/C/Rlibs/R.framework/Versions/3.2/Resources/include/Rmath.h:339</i>
	 */
	double rnorm(double double1, double double2);
	/**
	 * both tails<br>
	 * Original signature : <code>void pnorm_both(double, double*, double*, int, int)</code><br>
	 * @param int2 both tails<br>
	 * <i>native declaration : /Users/eralljn/Research/Coding/C/Rlibs/R.framework/Versions/3.2/Resources/include/Rmath.h:340</i><br>
	 * @deprecated use the safer methods {@link #pnorm_both(double, java.nio.DoubleBuffer, java.nio.DoubleBuffer, int, int)} and {@link #pnorm_both(double, com.sun.jna.ptr.DoubleByReference, com.sun.jna.ptr.DoubleByReference, int, int)} instead
	 */
	@Deprecated 
	void pnorm_both(double double1, DoubleByReference doublePtr1, DoubleByReference doublePtr2, int int1, int int2);
	/**
	 * both tails<br>
	 * Original signature : <code>void pnorm_both(double, double*, double*, int, int)</code><br>
	 * @param int2 both tails<br>
	 * <i>native declaration : /Users/eralljn/Research/Coding/C/Rlibs/R.framework/Versions/3.2/Resources/include/Rmath.h:340</i>
	 */
	void pnorm_both(double double1, DoubleBuffer doublePtr1, DoubleBuffer doublePtr2, int int1, int int2);
	/**
	 * Original signature : <code>double dunif(double, double, double, int)</code><br>
	 * <i>native declaration : /Users/eralljn/Research/Coding/C/Rlibs/R.framework/Versions/3.2/Resources/include/Rmath.h:344</i>
	 */
	double dunif(double double1, double double2, double double3, int int1);
	/**
	 * Original signature : <code>double punif(double, double, double, int, int)</code><br>
	 * <i>native declaration : /Users/eralljn/Research/Coding/C/Rlibs/R.framework/Versions/3.2/Resources/include/Rmath.h:345</i>
	 */
	double punif(double double1, double double2, double double3, int int1, int int2);
	/**
	 * Original signature : <code>double qunif(double, double, double, int, int)</code><br>
	 * <i>native declaration : /Users/eralljn/Research/Coding/C/Rlibs/R.framework/Versions/3.2/Resources/include/Rmath.h:346</i>
	 */
	double qunif(double double1, double double2, double double3, int int1, int int2);
	/**
	 * Original signature : <code>double runif(double, double)</code><br>
	 * <i>native declaration : /Users/eralljn/Research/Coding/C/Rlibs/R.framework/Versions/3.2/Resources/include/Rmath.h:347</i>
	 */
	double runif(double double1, double double2);
	/**
	 * Original signature : <code>double dgamma(double, double, double, int)</code><br>
	 * <i>native declaration : /Users/eralljn/Research/Coding/C/Rlibs/R.framework/Versions/3.2/Resources/include/Rmath.h:351</i>
	 */
	double dgamma(double double1, double double2, double double3, int int1);
	/**
	 * Original signature : <code>double pgamma(double, double, double, int, int)</code><br>
	 * <i>native declaration : /Users/eralljn/Research/Coding/C/Rlibs/R.framework/Versions/3.2/Resources/include/Rmath.h:352</i>
	 */
	double pgamma(double double1, double double2, double double3, int int1, int int2);
	/**
	 * Original signature : <code>double qgamma(double, double, double, int, int)</code><br>
	 * <i>native declaration : /Users/eralljn/Research/Coding/C/Rlibs/R.framework/Versions/3.2/Resources/include/Rmath.h:353</i>
	 */
	double qgamma(double double1, double double2, double double3, int int1, int int2);
	/**
	 * Original signature : <code>double rgamma(double, double)</code><br>
	 * <i>native declaration : /Users/eralljn/Research/Coding/C/Rlibs/R.framework/Versions/3.2/Resources/include/Rmath.h:354</i>
	 */
	double rgamma(double double1, double double2);
	/**
	 * Original signature : <code>double log1pmx(double)</code><br>
	 * <i>native declaration : /Users/eralljn/Research/Coding/C/Rlibs/R.framework/Versions/3.2/Resources/include/Rmath.h:356</i>
	 */
	double log1pmx(double double1);
	/**
	 * <-- ../nmath/plogis.c<br>
	 * Original signature : <code>double log1pexp(double)</code><br>
	 * @param double1 <-- ../nmath/plogis.c<br>
	 * <i>native declaration : /Users/eralljn/Research/Coding/C/Rlibs/R.framework/Versions/3.2/Resources/include/Rmath.h:357</i>
	 */
	double log1pexp(double double1);
	/**
	 * Original signature : <code>double lgamma1p(double)</code><br>
	 * <i>native declaration : /Users/eralljn/Research/Coding/C/Rlibs/R.framework/Versions/3.2/Resources/include/Rmath.h:358</i>
	 */
	double lgamma1p(double double1);
	/**
	 * Original signature : <code>double logspace_add(double, double)</code><br>
	 * <i>native declaration : /Users/eralljn/Research/Coding/C/Rlibs/R.framework/Versions/3.2/Resources/include/Rmath.h:359</i>
	 */
	double logspace_add(double double1, double double2);
	/**
	 * Original signature : <code>double logspace_sub(double, double)</code><br>
	 * <i>native declaration : /Users/eralljn/Research/Coding/C/Rlibs/R.framework/Versions/3.2/Resources/include/Rmath.h:360</i>
	 */
	double logspace_sub(double double1, double double2);
	/**
	 * Original signature : <code>double logspace_sum(double*, int)</code><br>
	 * <i>native declaration : /Users/eralljn/Research/Coding/C/Rlibs/R.framework/Versions/3.2/Resources/include/Rmath.h:361</i><br>
	 * @deprecated use the safer methods {@link #logspace_sum(java.nio.DoubleBuffer, int)} and {@link #logspace_sum(com.sun.jna.ptr.DoubleByReference, int)} instead
	 */
	@Deprecated 
	double logspace_sum(DoubleByReference doublePtr1, int int1);
	/**
	 * Original signature : <code>double logspace_sum(double*, int)</code><br>
	 * <i>native declaration : /Users/eralljn/Research/Coding/C/Rlibs/R.framework/Versions/3.2/Resources/include/Rmath.h:361</i>
	 */
	double logspace_sum(DoubleBuffer doublePtr1, int int1);
	/**
	 * Original signature : <code>double dbeta(double, double, double, int)</code><br>
	 * <i>native declaration : /Users/eralljn/Research/Coding/C/Rlibs/R.framework/Versions/3.2/Resources/include/Rmath.h:365</i>
	 */
	double dbeta(double double1, double double2, double double3, int int1);
	/**
	 * Original signature : <code>double pbeta(double, double, double, int, int)</code><br>
	 * <i>native declaration : /Users/eralljn/Research/Coding/C/Rlibs/R.framework/Versions/3.2/Resources/include/Rmath.h:366</i>
	 */
	double pbeta(double double1, double double2, double double3, int int1, int int2);
	/**
	 * Original signature : <code>double qbeta(double, double, double, int, int)</code><br>
	 * <i>native declaration : /Users/eralljn/Research/Coding/C/Rlibs/R.framework/Versions/3.2/Resources/include/Rmath.h:367</i>
	 */
	double qbeta(double double1, double double2, double double3, int int1, int int2);
	/**
	 * Original signature : <code>double rbeta(double, double)</code><br>
	 * <i>native declaration : /Users/eralljn/Research/Coding/C/Rlibs/R.framework/Versions/3.2/Resources/include/Rmath.h:368</i>
	 */
	double rbeta(double double1, double double2);
	/**
	 * Original signature : <code>double dlnorm(double, double, double, int)</code><br>
	 * <i>native declaration : /Users/eralljn/Research/Coding/C/Rlibs/R.framework/Versions/3.2/Resources/include/Rmath.h:372</i>
	 */
	double dlnorm(double double1, double double2, double double3, int int1);
	/**
	 * Original signature : <code>double plnorm(double, double, double, int, int)</code><br>
	 * <i>native declaration : /Users/eralljn/Research/Coding/C/Rlibs/R.framework/Versions/3.2/Resources/include/Rmath.h:373</i>
	 */
	double plnorm(double double1, double double2, double double3, int int1, int int2);
	/**
	 * Original signature : <code>double qlnorm(double, double, double, int, int)</code><br>
	 * <i>native declaration : /Users/eralljn/Research/Coding/C/Rlibs/R.framework/Versions/3.2/Resources/include/Rmath.h:374</i>
	 */
	double qlnorm(double double1, double double2, double double3, int int1, int int2);
	/**
	 * Original signature : <code>double rlnorm(double, double)</code><br>
	 * <i>native declaration : /Users/eralljn/Research/Coding/C/Rlibs/R.framework/Versions/3.2/Resources/include/Rmath.h:375</i>
	 */
	double rlnorm(double double1, double double2);
	/**
	 * Original signature : <code>double dchisq(double, double, int)</code><br>
	 * <i>native declaration : /Users/eralljn/Research/Coding/C/Rlibs/R.framework/Versions/3.2/Resources/include/Rmath.h:379</i>
	 */
	double dchisq(double double1, double double2, int int1);
	/**
	 * Original signature : <code>double pchisq(double, double, int, int)</code><br>
	 * <i>native declaration : /Users/eralljn/Research/Coding/C/Rlibs/R.framework/Versions/3.2/Resources/include/Rmath.h:380</i>
	 */
	double pchisq(double double1, double double2, int int1, int int2);
	/**
	 * Original signature : <code>double qchisq(double, double, int, int)</code><br>
	 * <i>native declaration : /Users/eralljn/Research/Coding/C/Rlibs/R.framework/Versions/3.2/Resources/include/Rmath.h:381</i>
	 */
	double qchisq(double double1, double double2, int int1, int int2);
	/**
	 * Original signature : <code>double rchisq(double)</code><br>
	 * <i>native declaration : /Users/eralljn/Research/Coding/C/Rlibs/R.framework/Versions/3.2/Resources/include/Rmath.h:382</i>
	 */
	double rchisq(double double1);
	/**
	 * Original signature : <code>double dnchisq(double, double, double, int)</code><br>
	 * <i>native declaration : /Users/eralljn/Research/Coding/C/Rlibs/R.framework/Versions/3.2/Resources/include/Rmath.h:386</i>
	 */
	double dnchisq(double double1, double double2, double double3, int int1);
	/**
	 * Original signature : <code>double pnchisq(double, double, double, int, int)</code><br>
	 * <i>native declaration : /Users/eralljn/Research/Coding/C/Rlibs/R.framework/Versions/3.2/Resources/include/Rmath.h:387</i>
	 */
	double pnchisq(double double1, double double2, double double3, int int1, int int2);
	/**
	 * Original signature : <code>double qnchisq(double, double, double, int, int)</code><br>
	 * <i>native declaration : /Users/eralljn/Research/Coding/C/Rlibs/R.framework/Versions/3.2/Resources/include/Rmath.h:388</i>
	 */
	double qnchisq(double double1, double double2, double double3, int int1, int int2);
	/**
	 * Original signature : <code>double rnchisq(double, double)</code><br>
	 * <i>native declaration : /Users/eralljn/Research/Coding/C/Rlibs/R.framework/Versions/3.2/Resources/include/Rmath.h:389</i>
	 */
	double rnchisq(double double1, double double2);
	/**
	 * Original signature : <code>double df(double, double, double, int)</code><br>
	 * <i>native declaration : /Users/eralljn/Research/Coding/C/Rlibs/R.framework/Versions/3.2/Resources/include/Rmath.h:393</i>
	 */
	double df(double double1, double double2, double double3, int int1);
	/**
	 * Original signature : <code>double pf(double, double, double, int, int)</code><br>
	 * <i>native declaration : /Users/eralljn/Research/Coding/C/Rlibs/R.framework/Versions/3.2/Resources/include/Rmath.h:394</i>
	 */
	double pf(double double1, double double2, double double3, int int1, int int2);
	/**
	 * Original signature : <code>double qf(double, double, double, int, int)</code><br>
	 * <i>native declaration : /Users/eralljn/Research/Coding/C/Rlibs/R.framework/Versions/3.2/Resources/include/Rmath.h:395</i>
	 */
	double qf(double double1, double double2, double double3, int int1, int int2);
	/**
	 * Original signature : <code>double rf(double, double)</code><br>
	 * <i>native declaration : /Users/eralljn/Research/Coding/C/Rlibs/R.framework/Versions/3.2/Resources/include/Rmath.h:396</i>
	 */
	double rf(double double1, double double2);
	/**
	 * Original signature : <code>double dt(double, double, int)</code><br>
	 * <i>native declaration : /Users/eralljn/Research/Coding/C/Rlibs/R.framework/Versions/3.2/Resources/include/Rmath.h:400</i>
	 */
	double dt(double double1, double double2, int int1);
	/**
	 * Original signature : <code>double pt(double, double, int, int)</code><br>
	 * <i>native declaration : /Users/eralljn/Research/Coding/C/Rlibs/R.framework/Versions/3.2/Resources/include/Rmath.h:401</i>
	 */
	double pt(double double1, double double2, int int1, int int2);
	/**
	 * Original signature : <code>double qt(double, double, int, int)</code><br>
	 * <i>native declaration : /Users/eralljn/Research/Coding/C/Rlibs/R.framework/Versions/3.2/Resources/include/Rmath.h:402</i>
	 */
	double qt(double double1, double double2, int int1, int int2);
	/**
	 * Original signature : <code>double rt(double)</code><br>
	 * <i>native declaration : /Users/eralljn/Research/Coding/C/Rlibs/R.framework/Versions/3.2/Resources/include/Rmath.h:403</i>
	 */
	double rt(double double1);
	/**
	 * Original signature : <code>double dbinom_raw(double, double, double, double, int)</code><br>
	 * <i>native declaration : /Users/eralljn/Research/Coding/C/Rlibs/R.framework/Versions/3.2/Resources/include/Rmath.h:407</i>
	 */
	double dbinom_raw(double x, double n, double p, double q, int give_log);
	/**
	 * Original signature : <code>double dbinom(double, double, double, int)</code><br>
	 * <i>native declaration : /Users/eralljn/Research/Coding/C/Rlibs/R.framework/Versions/3.2/Resources/include/Rmath.h:408</i>
	 */
	double dbinom(double double1, double double2, double double3, int int1);
	/**
	 * Original signature : <code>double pbinom(double, double, double, int, int)</code><br>
	 * <i>native declaration : /Users/eralljn/Research/Coding/C/Rlibs/R.framework/Versions/3.2/Resources/include/Rmath.h:409</i>
	 */
	double pbinom(double double1, double double2, double double3, int int1, int int2);
	/**
	 * Original signature : <code>double qbinom(double, double, double, int, int)</code><br>
	 * <i>native declaration : /Users/eralljn/Research/Coding/C/Rlibs/R.framework/Versions/3.2/Resources/include/Rmath.h:410</i>
	 */
	double qbinom(double double1, double double2, double double3, int int1, int int2);
	/**
	 * Original signature : <code>double rbinom(double, double)</code><br>
	 * <i>native declaration : /Users/eralljn/Research/Coding/C/Rlibs/R.framework/Versions/3.2/Resources/include/Rmath.h:411</i>
	 */
	double rbinom(double double1, double double2);
	/**
	 * Original signature : <code>void rmultinom(int, double*, int, int*)</code><br>
	 * <i>native declaration : /Users/eralljn/Research/Coding/C/Rlibs/R.framework/Versions/3.2/Resources/include/Rmath.h:415</i><br>
	 * @deprecated use the safer methods {@link #rmultinom(int, java.nio.DoubleBuffer, int, java.nio.IntBuffer)} and {@link #rmultinom(int, com.sun.jna.ptr.DoubleByReference, int, com.sun.jna.ptr.IntByReference)} instead
	 */
	@Deprecated 
	void rmultinom(int int1, DoubleByReference doublePtr1, int int2, IntByReference intPtr1);
	/**
	 * Original signature : <code>void rmultinom(int, double*, int, int*)</code><br>
	 * <i>native declaration : /Users/eralljn/Research/Coding/C/Rlibs/R.framework/Versions/3.2/Resources/include/Rmath.h:415</i>
	 */
	void rmultinom(int int1, DoubleBuffer doublePtr1, int int2, IntBuffer intPtr1);
	/**
	 * Original signature : <code>double dcauchy(double, double, double, int)</code><br>
	 * <i>native declaration : /Users/eralljn/Research/Coding/C/Rlibs/R.framework/Versions/3.2/Resources/include/Rmath.h:419</i>
	 */
	double dcauchy(double double1, double double2, double double3, int int1);
	/**
	 * Original signature : <code>double pcauchy(double, double, double, int, int)</code><br>
	 * <i>native declaration : /Users/eralljn/Research/Coding/C/Rlibs/R.framework/Versions/3.2/Resources/include/Rmath.h:420</i>
	 */
	double pcauchy(double double1, double double2, double double3, int int1, int int2);
	/**
	 * Original signature : <code>double qcauchy(double, double, double, int, int)</code><br>
	 * <i>native declaration : /Users/eralljn/Research/Coding/C/Rlibs/R.framework/Versions/3.2/Resources/include/Rmath.h:421</i>
	 */
	double qcauchy(double double1, double double2, double double3, int int1, int int2);
	/**
	 * Original signature : <code>double rcauchy(double, double)</code><br>
	 * <i>native declaration : /Users/eralljn/Research/Coding/C/Rlibs/R.framework/Versions/3.2/Resources/include/Rmath.h:422</i>
	 */
	double rcauchy(double double1, double double2);
	/**
	 * Original signature : <code>double dexp(double, double, int)</code><br>
	 * <i>native declaration : /Users/eralljn/Research/Coding/C/Rlibs/R.framework/Versions/3.2/Resources/include/Rmath.h:426</i>
	 */
	double dexp(double double1, double double2, int int1);
	/**
	 * Original signature : <code>double pexp(double, double, int, int)</code><br>
	 * <i>native declaration : /Users/eralljn/Research/Coding/C/Rlibs/R.framework/Versions/3.2/Resources/include/Rmath.h:427</i>
	 */
	double pexp(double double1, double double2, int int1, int int2);
	/**
	 * Original signature : <code>double qexp(double, double, int, int)</code><br>
	 * <i>native declaration : /Users/eralljn/Research/Coding/C/Rlibs/R.framework/Versions/3.2/Resources/include/Rmath.h:428</i>
	 */
	double qexp(double double1, double double2, int int1, int int2);
	/**
	 * Original signature : <code>double rexp(double)</code><br>
	 * <i>native declaration : /Users/eralljn/Research/Coding/C/Rlibs/R.framework/Versions/3.2/Resources/include/Rmath.h:429</i>
	 */
	double rexp(double double1);
	/**
	 * Original signature : <code>double dgeom(double, double, int)</code><br>
	 * <i>native declaration : /Users/eralljn/Research/Coding/C/Rlibs/R.framework/Versions/3.2/Resources/include/Rmath.h:433</i>
	 */
	double dgeom(double double1, double double2, int int1);
	/**
	 * Original signature : <code>double pgeom(double, double, int, int)</code><br>
	 * <i>native declaration : /Users/eralljn/Research/Coding/C/Rlibs/R.framework/Versions/3.2/Resources/include/Rmath.h:434</i>
	 */
	double pgeom(double double1, double double2, int int1, int int2);
	/**
	 * Original signature : <code>double qgeom(double, double, int, int)</code><br>
	 * <i>native declaration : /Users/eralljn/Research/Coding/C/Rlibs/R.framework/Versions/3.2/Resources/include/Rmath.h:435</i>
	 */
	double qgeom(double double1, double double2, int int1, int int2);
	/**
	 * Original signature : <code>double rgeom(double)</code><br>
	 * <i>native declaration : /Users/eralljn/Research/Coding/C/Rlibs/R.framework/Versions/3.2/Resources/include/Rmath.h:436</i>
	 */
	double rgeom(double double1);
	/**
	 * Original signature : <code>double dhyper(double, double, double, double, int)</code><br>
	 * <i>native declaration : /Users/eralljn/Research/Coding/C/Rlibs/R.framework/Versions/3.2/Resources/include/Rmath.h:440</i>
	 */
	double dhyper(double double1, double double2, double double3, double double4, int int1);
	/**
	 * Original signature : <code>double phyper(double, double, double, double, int, int)</code><br>
	 * <i>native declaration : /Users/eralljn/Research/Coding/C/Rlibs/R.framework/Versions/3.2/Resources/include/Rmath.h:441</i>
	 */
	double phyper(double double1, double double2, double double3, double double4, int int1, int int2);
	/**
	 * Original signature : <code>double qhyper(double, double, double, double, int, int)</code><br>
	 * <i>native declaration : /Users/eralljn/Research/Coding/C/Rlibs/R.framework/Versions/3.2/Resources/include/Rmath.h:442</i>
	 */
	double qhyper(double double1, double double2, double double3, double double4, int int1, int int2);
	/**
	 * Original signature : <code>double rhyper(double, double, double)</code><br>
	 * <i>native declaration : /Users/eralljn/Research/Coding/C/Rlibs/R.framework/Versions/3.2/Resources/include/Rmath.h:443</i>
	 */
	double rhyper(double double1, double double2, double double3);
	/**
	 * Original signature : <code>double dnbinom(double, double, double, int)</code><br>
	 * <i>native declaration : /Users/eralljn/Research/Coding/C/Rlibs/R.framework/Versions/3.2/Resources/include/Rmath.h:447</i>
	 */
	double dnbinom(double double1, double double2, double double3, int int1);
	/**
	 * Original signature : <code>double pnbinom(double, double, double, int, int)</code><br>
	 * <i>native declaration : /Users/eralljn/Research/Coding/C/Rlibs/R.framework/Versions/3.2/Resources/include/Rmath.h:448</i>
	 */
	double pnbinom(double double1, double double2, double double3, int int1, int int2);
	/**
	 * Original signature : <code>double qnbinom(double, double, double, int, int)</code><br>
	 * <i>native declaration : /Users/eralljn/Research/Coding/C/Rlibs/R.framework/Versions/3.2/Resources/include/Rmath.h:449</i>
	 */
	double qnbinom(double double1, double double2, double double3, int int1, int int2);
	/**
	 * Original signature : <code>double rnbinom(double, double)</code><br>
	 * <i>native declaration : /Users/eralljn/Research/Coding/C/Rlibs/R.framework/Versions/3.2/Resources/include/Rmath.h:450</i>
	 */
	double rnbinom(double double1, double double2);
	/**
	 * Original signature : <code>double dnbinom_mu(double, double, double, int)</code><br>
	 * <i>native declaration : /Users/eralljn/Research/Coding/C/Rlibs/R.framework/Versions/3.2/Resources/include/Rmath.h:452</i>
	 */
	double dnbinom_mu(double double1, double double2, double double3, int int1);
	/**
	 * Original signature : <code>double pnbinom_mu(double, double, double, int, int)</code><br>
	 * <i>native declaration : /Users/eralljn/Research/Coding/C/Rlibs/R.framework/Versions/3.2/Resources/include/Rmath.h:453</i>
	 */
	double pnbinom_mu(double double1, double double2, double double3, int int1, int int2);
	/**
	 * Original signature : <code>double qnbinom_mu(double, double, double, int, int)</code><br>
	 * <i>native declaration : /Users/eralljn/Research/Coding/C/Rlibs/R.framework/Versions/3.2/Resources/include/Rmath.h:454</i>
	 */
	double qnbinom_mu(double double1, double double2, double double3, int int1, int int2);
	/**
	 * Original signature : <code>double rnbinom_mu(double, double)</code><br>
	 * <i>native declaration : /Users/eralljn/Research/Coding/C/Rlibs/R.framework/Versions/3.2/Resources/include/Rmath.h:455</i>
	 */
	double rnbinom_mu(double double1, double double2);
	/**
	 * Original signature : <code>double dpois_raw(double, double, int)</code><br>
	 * <i>native declaration : /Users/eralljn/Research/Coding/C/Rlibs/R.framework/Versions/3.2/Resources/include/Rmath.h:459</i>
	 */
	double dpois_raw(double double1, double double2, int int1);
	/**
	 * Original signature : <code>double dpois(double, double, int)</code><br>
	 * <i>native declaration : /Users/eralljn/Research/Coding/C/Rlibs/R.framework/Versions/3.2/Resources/include/Rmath.h:460</i>
	 */
	double dpois(double double1, double double2, int int1);
	/**
	 * Original signature : <code>double ppois(double, double, int, int)</code><br>
	 * <i>native declaration : /Users/eralljn/Research/Coding/C/Rlibs/R.framework/Versions/3.2/Resources/include/Rmath.h:461</i>
	 */
	double ppois(double double1, double double2, int int1, int int2);
	/**
	 * Original signature : <code>double qpois(double, double, int, int)</code><br>
	 * <i>native declaration : /Users/eralljn/Research/Coding/C/Rlibs/R.framework/Versions/3.2/Resources/include/Rmath.h:462</i>
	 */
	double qpois(double double1, double double2, int int1, int int2);
	/**
	 * Original signature : <code>double rpois(double)</code><br>
	 * <i>native declaration : /Users/eralljn/Research/Coding/C/Rlibs/R.framework/Versions/3.2/Resources/include/Rmath.h:463</i>
	 */
	double rpois(double double1);
	/**
	 * Original signature : <code>double dweibull(double, double, double, int)</code><br>
	 * <i>native declaration : /Users/eralljn/Research/Coding/C/Rlibs/R.framework/Versions/3.2/Resources/include/Rmath.h:467</i>
	 */
	double dweibull(double double1, double double2, double double3, int int1);
	/**
	 * Original signature : <code>double pweibull(double, double, double, int, int)</code><br>
	 * <i>native declaration : /Users/eralljn/Research/Coding/C/Rlibs/R.framework/Versions/3.2/Resources/include/Rmath.h:468</i>
	 */
	double pweibull(double double1, double double2, double double3, int int1, int int2);
	/**
	 * Original signature : <code>double qweibull(double, double, double, int, int)</code><br>
	 * <i>native declaration : /Users/eralljn/Research/Coding/C/Rlibs/R.framework/Versions/3.2/Resources/include/Rmath.h:469</i>
	 */
	double qweibull(double double1, double double2, double double3, int int1, int int2);
	/**
	 * Original signature : <code>double rweibull(double, double)</code><br>
	 * <i>native declaration : /Users/eralljn/Research/Coding/C/Rlibs/R.framework/Versions/3.2/Resources/include/Rmath.h:470</i>
	 */
	double rweibull(double double1, double double2);
	/**
	 * Original signature : <code>double dlogis(double, double, double, int)</code><br>
	 * <i>native declaration : /Users/eralljn/Research/Coding/C/Rlibs/R.framework/Versions/3.2/Resources/include/Rmath.h:474</i>
	 */
	double dlogis(double double1, double double2, double double3, int int1);
	/**
	 * Original signature : <code>double plogis(double, double, double, int, int)</code><br>
	 * <i>native declaration : /Users/eralljn/Research/Coding/C/Rlibs/R.framework/Versions/3.2/Resources/include/Rmath.h:475</i>
	 */
	double plogis(double double1, double double2, double double3, int int1, int int2);
	/**
	 * Original signature : <code>double qlogis(double, double, double, int, int)</code><br>
	 * <i>native declaration : /Users/eralljn/Research/Coding/C/Rlibs/R.framework/Versions/3.2/Resources/include/Rmath.h:476</i>
	 */
	double qlogis(double double1, double double2, double double3, int int1, int int2);
	/**
	 * Original signature : <code>double rlogis(double, double)</code><br>
	 * <i>native declaration : /Users/eralljn/Research/Coding/C/Rlibs/R.framework/Versions/3.2/Resources/include/Rmath.h:477</i>
	 */
	double rlogis(double double1, double double2);
	/**
	 * Original signature : <code>double dnbeta(double, double, double, double, int)</code><br>
	 * <i>native declaration : /Users/eralljn/Research/Coding/C/Rlibs/R.framework/Versions/3.2/Resources/include/Rmath.h:481</i>
	 */
	double dnbeta(double double1, double double2, double double3, double double4, int int1);
	/**
	 * Original signature : <code>double pnbeta(double, double, double, double, int, int)</code><br>
	 * <i>native declaration : /Users/eralljn/Research/Coding/C/Rlibs/R.framework/Versions/3.2/Resources/include/Rmath.h:482</i>
	 */
	double pnbeta(double double1, double double2, double double3, double double4, int int1, int int2);
	/**
	 * Original signature : <code>double qnbeta(double, double, double, double, int, int)</code><br>
	 * <i>native declaration : /Users/eralljn/Research/Coding/C/Rlibs/R.framework/Versions/3.2/Resources/include/Rmath.h:483</i>
	 */
	double qnbeta(double double1, double double2, double double3, double double4, int int1, int int2);
	/**
	 * Original signature : <code>double rnbeta(double, double, double)</code><br>
	 * <i>native declaration : /Users/eralljn/Research/Coding/C/Rlibs/R.framework/Versions/3.2/Resources/include/Rmath.h:484</i>
	 */
	double rnbeta(double double1, double double2, double double3);
	/**
	 * Original signature : <code>double dnf(double, double, double, double, int)</code><br>
	 * <i>native declaration : /Users/eralljn/Research/Coding/C/Rlibs/R.framework/Versions/3.2/Resources/include/Rmath.h:488</i>
	 */
	double dnf(double double1, double double2, double double3, double double4, int int1);
	/**
	 * Original signature : <code>double pnf(double, double, double, double, int, int)</code><br>
	 * <i>native declaration : /Users/eralljn/Research/Coding/C/Rlibs/R.framework/Versions/3.2/Resources/include/Rmath.h:489</i>
	 */
	double pnf(double double1, double double2, double double3, double double4, int int1, int int2);
	/**
	 * Original signature : <code>double qnf(double, double, double, double, int, int)</code><br>
	 * <i>native declaration : /Users/eralljn/Research/Coding/C/Rlibs/R.framework/Versions/3.2/Resources/include/Rmath.h:490</i>
	 */
	double qnf(double double1, double double2, double double3, double double4, int int1, int int2);
	/**
	 * Original signature : <code>double dnt(double, double, double, int)</code><br>
	 * <i>native declaration : /Users/eralljn/Research/Coding/C/Rlibs/R.framework/Versions/3.2/Resources/include/Rmath.h:494</i>
	 */
	double dnt(double double1, double double2, double double3, int int1);
	/**
	 * Original signature : <code>double pnt(double, double, double, int, int)</code><br>
	 * <i>native declaration : /Users/eralljn/Research/Coding/C/Rlibs/R.framework/Versions/3.2/Resources/include/Rmath.h:495</i>
	 */
	double pnt(double double1, double double2, double double3, int int1, int int2);
	/**
	 * Original signature : <code>double qnt(double, double, double, int, int)</code><br>
	 * <i>native declaration : /Users/eralljn/Research/Coding/C/Rlibs/R.framework/Versions/3.2/Resources/include/Rmath.h:496</i>
	 */
	double qnt(double double1, double double2, double double3, int int1, int int2);
	/**
	 * Original signature : <code>double ptukey(double, double, double, double, int, int)</code><br>
	 * <i>native declaration : /Users/eralljn/Research/Coding/C/Rlibs/R.framework/Versions/3.2/Resources/include/Rmath.h:500</i>
	 */
	double ptukey(double double1, double double2, double double3, double double4, int int1, int int2);
	/**
	 * Original signature : <code>double qtukey(double, double, double, double, int, int)</code><br>
	 * <i>native declaration : /Users/eralljn/Research/Coding/C/Rlibs/R.framework/Versions/3.2/Resources/include/Rmath.h:501</i>
	 */
	double qtukey(double double1, double double2, double double3, double double4, int int1, int int2);
	/**
	 * Original signature : <code>double dwilcox(double, double, double, int)</code><br>
	 * <i>native declaration : /Users/eralljn/Research/Coding/C/Rlibs/R.framework/Versions/3.2/Resources/include/Rmath.h:505</i>
	 */
	double dwilcox(double double1, double double2, double double3, int int1);
	/**
	 * Original signature : <code>double pwilcox(double, double, double, int, int)</code><br>
	 * <i>native declaration : /Users/eralljn/Research/Coding/C/Rlibs/R.framework/Versions/3.2/Resources/include/Rmath.h:506</i>
	 */
	double pwilcox(double double1, double double2, double double3, int int1, int int2);
	/**
	 * Original signature : <code>double qwilcox(double, double, double, int, int)</code><br>
	 * <i>native declaration : /Users/eralljn/Research/Coding/C/Rlibs/R.framework/Versions/3.2/Resources/include/Rmath.h:507</i>
	 */
	double qwilcox(double double1, double double2, double double3, int int1, int int2);
	/**
	 * Original signature : <code>double rwilcox(double, double)</code><br>
	 * <i>native declaration : /Users/eralljn/Research/Coding/C/Rlibs/R.framework/Versions/3.2/Resources/include/Rmath.h:508</i>
	 */
	double rwilcox(double double1, double double2);
	/**
	 * Original signature : <code>double dsignrank(double, double, int)</code><br>
	 * <i>native declaration : /Users/eralljn/Research/Coding/C/Rlibs/R.framework/Versions/3.2/Resources/include/Rmath.h:512</i>
	 */
	double dsignrank(double double1, double double2, int int1);
	/**
	 * Original signature : <code>double psignrank(double, double, int, int)</code><br>
	 * <i>native declaration : /Users/eralljn/Research/Coding/C/Rlibs/R.framework/Versions/3.2/Resources/include/Rmath.h:513</i>
	 */
	double psignrank(double double1, double double2, int int1, int int2);
	/**
	 * Original signature : <code>double qsignrank(double, double, int, int)</code><br>
	 * <i>native declaration : /Users/eralljn/Research/Coding/C/Rlibs/R.framework/Versions/3.2/Resources/include/Rmath.h:514</i>
	 */
	double qsignrank(double double1, double double2, int int1, int int2);
	/**
	 * Original signature : <code>double rsignrank(double)</code><br>
	 * <i>native declaration : /Users/eralljn/Research/Coding/C/Rlibs/R.framework/Versions/3.2/Resources/include/Rmath.h:515</i>
	 */
	double rsignrank(double double1);
	/**
	 * Original signature : <code>double gammafn(double)</code><br>
	 * <i>native declaration : /Users/eralljn/Research/Coding/C/Rlibs/R.framework/Versions/3.2/Resources/include/Rmath.h:518</i>
	 */
	double gammafn(double double1);
	/**
	 * Original signature : <code>double lgammafn(double)</code><br>
	 * <i>native declaration : /Users/eralljn/Research/Coding/C/Rlibs/R.framework/Versions/3.2/Resources/include/Rmath.h:519</i>
	 */
	double lgammafn(double double1);
	/**
	 * Original signature : <code>double lgammafn_sign(double, int*)</code><br>
	 * <i>native declaration : /Users/eralljn/Research/Coding/C/Rlibs/R.framework/Versions/3.2/Resources/include/Rmath.h:520</i><br>
	 * @deprecated use the safer methods {@link #lgammafn_sign(double, java.nio.IntBuffer)} and {@link #lgammafn_sign(double, com.sun.jna.ptr.IntByReference)} instead
	 */
	@Deprecated 
	double lgammafn_sign(double double1, IntByReference intPtr1);
	/**
	 * Original signature : <code>double lgammafn_sign(double, int*)</code><br>
	 * <i>native declaration : /Users/eralljn/Research/Coding/C/Rlibs/R.framework/Versions/3.2/Resources/include/Rmath.h:520</i>
	 */
	double lgammafn_sign(double double1, IntBuffer intPtr1);
	/**
	 * Original signature : <code>void dpsifn(double, int, int, int, double*, int*, int*)</code><br>
	 * <i>native declaration : /Users/eralljn/Research/Coding/C/Rlibs/R.framework/Versions/3.2/Resources/include/Rmath.h:521</i><br>
	 * @deprecated use the safer methods {@link #dpsifn(double, int, int, int, java.nio.DoubleBuffer, java.nio.IntBuffer, java.nio.IntBuffer)} and {@link #dpsifn(double, int, int, int, com.sun.jna.ptr.DoubleByReference, com.sun.jna.ptr.IntByReference, com.sun.jna.ptr.IntByReference)} instead
	 */
	@Deprecated 
	void dpsifn(double double1, int int1, int int2, int int3, DoubleByReference doublePtr1, IntByReference intPtr1, IntByReference intPtr2);
	/**
	 * Original signature : <code>void dpsifn(double, int, int, int, double*, int*, int*)</code><br>
	 * <i>native declaration : /Users/eralljn/Research/Coding/C/Rlibs/R.framework/Versions/3.2/Resources/include/Rmath.h:521</i>
	 */
	void dpsifn(double double1, int int1, int int2, int int3, DoubleBuffer doublePtr1, IntBuffer intPtr1, IntBuffer intPtr2);
	/**
	 * Original signature : <code>double psigamma(double, double)</code><br>
	 * <i>native declaration : /Users/eralljn/Research/Coding/C/Rlibs/R.framework/Versions/3.2/Resources/include/Rmath.h:522</i>
	 */
	double psigamma(double double1, double double2);
	/**
	 * Original signature : <code>double digamma(double)</code><br>
	 * <i>native declaration : /Users/eralljn/Research/Coding/C/Rlibs/R.framework/Versions/3.2/Resources/include/Rmath.h:523</i>
	 */
	double digamma(double double1);
	/**
	 * Original signature : <code>double trigamma(double)</code><br>
	 * <i>native declaration : /Users/eralljn/Research/Coding/C/Rlibs/R.framework/Versions/3.2/Resources/include/Rmath.h:524</i>
	 */
	double trigamma(double double1);
	/**
	 * Original signature : <code>double tetragamma(double)</code><br>
	 * <i>native declaration : /Users/eralljn/Research/Coding/C/Rlibs/R.framework/Versions/3.2/Resources/include/Rmath.h:525</i>
	 */
	double tetragamma(double double1);
	/**
	 * Original signature : <code>double pentagamma(double)</code><br>
	 * <i>native declaration : /Users/eralljn/Research/Coding/C/Rlibs/R.framework/Versions/3.2/Resources/include/Rmath.h:526</i>
	 */
	double pentagamma(double double1);
	/**
	 * Original signature : <code>double beta(double, double)</code><br>
	 * <i>native declaration : /Users/eralljn/Research/Coding/C/Rlibs/R.framework/Versions/3.2/Resources/include/Rmath.h:528</i>
	 */
	double beta(double double1, double double2);
	/**
	 * Original signature : <code>double lbeta(double, double)</code><br>
	 * <i>native declaration : /Users/eralljn/Research/Coding/C/Rlibs/R.framework/Versions/3.2/Resources/include/Rmath.h:529</i>
	 */
	double lbeta(double double1, double double2);
	/**
	 * Original signature : <code>double choose(double, double)</code><br>
	 * <i>native declaration : /Users/eralljn/Research/Coding/C/Rlibs/R.framework/Versions/3.2/Resources/include/Rmath.h:531</i>
	 */
	double choose(double double1, double double2);
	/**
	 * Original signature : <code>double lchoose(double, double)</code><br>
	 * <i>native declaration : /Users/eralljn/Research/Coding/C/Rlibs/R.framework/Versions/3.2/Resources/include/Rmath.h:532</i>
	 */
	double lchoose(double double1, double double2);
	/**
	 * Original signature : <code>double bessel_i(double, double, double)</code><br>
	 * <i>native declaration : /Users/eralljn/Research/Coding/C/Rlibs/R.framework/Versions/3.2/Resources/include/Rmath.h:536</i>
	 */
	double bessel_i(double double1, double double2, double double3);
	/**
	 * Original signature : <code>double bessel_j(double, double)</code><br>
	 * <i>native declaration : /Users/eralljn/Research/Coding/C/Rlibs/R.framework/Versions/3.2/Resources/include/Rmath.h:537</i>
	 */
	double bessel_j(double double1, double double2);
	/**
	 * Original signature : <code>double bessel_k(double, double, double)</code><br>
	 * <i>native declaration : /Users/eralljn/Research/Coding/C/Rlibs/R.framework/Versions/3.2/Resources/include/Rmath.h:538</i>
	 */
	double bessel_k(double double1, double double2, double double3);
	/**
	 * Original signature : <code>double bessel_y(double, double)</code><br>
	 * <i>native declaration : /Users/eralljn/Research/Coding/C/Rlibs/R.framework/Versions/3.2/Resources/include/Rmath.h:539</i>
	 */
	double bessel_y(double double1, double double2);
	/**
	 * Original signature : <code>double bessel_i_ex(double, double, double, double*)</code><br>
	 * <i>native declaration : /Users/eralljn/Research/Coding/C/Rlibs/R.framework/Versions/3.2/Resources/include/Rmath.h:540</i><br>
	 * @deprecated use the safer methods {@link #bessel_i_ex(double, double, double, java.nio.DoubleBuffer)} and {@link #bessel_i_ex(double, double, double, com.sun.jna.ptr.DoubleByReference)} instead
	 */
	@Deprecated 
	double bessel_i_ex(double double1, double double2, double double3, DoubleByReference doublePtr1);
	/**
	 * Original signature : <code>double bessel_i_ex(double, double, double, double*)</code><br>
	 * <i>native declaration : /Users/eralljn/Research/Coding/C/Rlibs/R.framework/Versions/3.2/Resources/include/Rmath.h:540</i>
	 */
	double bessel_i_ex(double double1, double double2, double double3, DoubleBuffer doublePtr1);
	/**
	 * Original signature : <code>double bessel_j_ex(double, double, double*)</code><br>
	 * <i>native declaration : /Users/eralljn/Research/Coding/C/Rlibs/R.framework/Versions/3.2/Resources/include/Rmath.h:541</i><br>
	 * @deprecated use the safer methods {@link #bessel_j_ex(double, double, java.nio.DoubleBuffer)} and {@link #bessel_j_ex(double, double, com.sun.jna.ptr.DoubleByReference)} instead
	 */
	@Deprecated 
	double bessel_j_ex(double double1, double double2, DoubleByReference doublePtr1);
	/**
	 * Original signature : <code>double bessel_j_ex(double, double, double*)</code><br>
	 * <i>native declaration : /Users/eralljn/Research/Coding/C/Rlibs/R.framework/Versions/3.2/Resources/include/Rmath.h:541</i>
	 */
	double bessel_j_ex(double double1, double double2, DoubleBuffer doublePtr1);
	/**
	 * Original signature : <code>double bessel_k_ex(double, double, double, double*)</code><br>
	 * <i>native declaration : /Users/eralljn/Research/Coding/C/Rlibs/R.framework/Versions/3.2/Resources/include/Rmath.h:542</i><br>
	 * @deprecated use the safer methods {@link #bessel_k_ex(double, double, double, java.nio.DoubleBuffer)} and {@link #bessel_k_ex(double, double, double, com.sun.jna.ptr.DoubleByReference)} instead
	 */
	@Deprecated 
	double bessel_k_ex(double double1, double double2, double double3, DoubleByReference doublePtr1);
	/**
	 * Original signature : <code>double bessel_k_ex(double, double, double, double*)</code><br>
	 * <i>native declaration : /Users/eralljn/Research/Coding/C/Rlibs/R.framework/Versions/3.2/Resources/include/Rmath.h:542</i>
	 */
	double bessel_k_ex(double double1, double double2, double double3, DoubleBuffer doublePtr1);
	/**
	 * Original signature : <code>double bessel_y_ex(double, double, double*)</code><br>
	 * <i>native declaration : /Users/eralljn/Research/Coding/C/Rlibs/R.framework/Versions/3.2/Resources/include/Rmath.h:543</i><br>
	 * @deprecated use the safer methods {@link #bessel_y_ex(double, double, java.nio.DoubleBuffer)} and {@link #bessel_y_ex(double, double, com.sun.jna.ptr.DoubleByReference)} instead
	 */
	@Deprecated 
	double bessel_y_ex(double double1, double double2, DoubleByReference doublePtr1);
	/**
	 * Original signature : <code>double bessel_y_ex(double, double, double*)</code><br>
	 * <i>native declaration : /Users/eralljn/Research/Coding/C/Rlibs/R.framework/Versions/3.2/Resources/include/Rmath.h:543</i>
	 */
	double bessel_y_ex(double double1, double double2, DoubleBuffer doublePtr1);
	/**
	 * Original signature : <code>double pythag(double, double)</code><br>
	 * <i>native declaration : /Users/eralljn/Research/Coding/C/Rlibs/R.framework/Versions/3.2/Resources/include/Rmath.h:551</i>
	 */
	double pythag(double double1, double double2);
	/**
	 * Original signature : <code>int imax2(int, int)</code><br>
	 * <i>native declaration : /Users/eralljn/Research/Coding/C/Rlibs/R.framework/Versions/3.2/Resources/include/Rmath.h:558</i>
	 */
	int imax2(int int1, int int2);
	/**
	 * Original signature : <code>int imin2(int, int)</code><br>
	 * <i>native declaration : /Users/eralljn/Research/Coding/C/Rlibs/R.framework/Versions/3.2/Resources/include/Rmath.h:559</i>
	 */
	int imin2(int int1, int int2);
	/**
	 * Original signature : <code>double fmax2(double, double)</code><br>
	 * <i>native declaration : /Users/eralljn/Research/Coding/C/Rlibs/R.framework/Versions/3.2/Resources/include/Rmath.h:560</i>
	 */
	double fmax2(double double1, double double2);
	/**
	 * Original signature : <code>double fmin2(double, double)</code><br>
	 * <i>native declaration : /Users/eralljn/Research/Coding/C/Rlibs/R.framework/Versions/3.2/Resources/include/Rmath.h:561</i>
	 */
	double fmin2(double double1, double double2);
	/**
	 * Original signature : <code>double sign(double)</code><br>
	 * <i>native declaration : /Users/eralljn/Research/Coding/C/Rlibs/R.framework/Versions/3.2/Resources/include/Rmath.h:562</i>
	 */
	double sign(double double1);
	/**
	 * Original signature : <code>double fprec(double, double)</code><br>
	 * <i>native declaration : /Users/eralljn/Research/Coding/C/Rlibs/R.framework/Versions/3.2/Resources/include/Rmath.h:563</i>
	 */
	double fprec(double double1, double double2);
	/**
	 * Original signature : <code>double fround(double, double)</code><br>
	 * <i>native declaration : /Users/eralljn/Research/Coding/C/Rlibs/R.framework/Versions/3.2/Resources/include/Rmath.h:564</i>
	 */
	double fround(double double1, double double2);
	/**
	 * Original signature : <code>double fsign(double, double)</code><br>
	 * <i>native declaration : /Users/eralljn/Research/Coding/C/Rlibs/R.framework/Versions/3.2/Resources/include/Rmath.h:565</i>
	 */
	double fsign(double double1, double double2);
	/**
	 * Original signature : <code>double ftrunc(double)</code><br>
	 * <i>native declaration : /Users/eralljn/Research/Coding/C/Rlibs/R.framework/Versions/3.2/Resources/include/Rmath.h:566</i>
	 */
	double ftrunc(double double1);
	/**
	 * More accurate cos(pi*x), sin(pi*x), tan(pi*x)<br>
	 * In future these declarations could clash with system headers if<br>
	 * someone had already included math.h with<br>
	 * __STDC_WANT_IEC_60559_TYPES_EXT__ defined.<br>
	 * We can add a check for that via the value of<br>
	 * __STDC_IEC_60559_FUNCS__ (>= 201ymmL, exact value not yet known).<br>
	 * Original signature : <code>double cospi(double)</code><br>
	 * <i>native declaration : /Users/eralljn/Research/Coding/C/Rlibs/R.framework/Versions/3.2/Resources/include/Rmath.h:579</i>
	 */
	double cospi(double double1);
	/**
	 * Original signature : <code>double sinpi(double)</code><br>
	 * <i>native declaration : /Users/eralljn/Research/Coding/C/Rlibs/R.framework/Versions/3.2/Resources/include/Rmath.h:580</i>
	 */
	double sinpi(double double1);
	/**
	 * Original signature : <code>double tanpi(double)</code><br>
	 * <i>native declaration : /Users/eralljn/Research/Coding/C/Rlibs/R.framework/Versions/3.2/Resources/include/Rmath.h:581</i>
	 */
	double tanpi(double double1);
	/**
	 * If isnan is a macro, as C99 specifies, the C++<br>
	 * math header will undefine it. This happens on OS X<br>
	 * in mlutils.c<br>
	 * Original signature : <code>int R_isnancpp(double)</code><br>
	 * @param double1 in mlutils.c<br>
	 * <i>native declaration : /Users/eralljn/Research/Coding/C/Rlibs/R.framework/Versions/3.2/Resources/include/Rmath.h:610</i>
	 */
	int R_isnancpp(double double1);
	/**
	 * Original signature : <code>int R_finite(double)</code><br>
	 * <i>native declaration : /Users/eralljn/Research/Coding/C/Rlibs/R.framework/Versions/3.2/Resources/include/Rmath.h:617</i>
	 */
	int R_finite(double double1);
}
